### ISSUE TITLE
Lab Information

### ISSUE THREAD

**Issue by tcaiazzi** [kwaku104/Virtualisation-of-Internet-Insecurity-Demonstration#1]
Hi @kwaku104,

I'm Tommaso, one of the maintainer of Kathará. We are collecting the best Kathará [labs from the community](https://github.com/KatharaFramework/Kathara-Labs/wiki/Community-Labs).

We are very interested in your lab, and we also love your GUI with "AlgorithmX". 

Can you please provide us an explanation on what exactly happens in the lab? 

Many thanks,
Tommaso

**Comment by kwaku104** [comment]
Hi @tcaiazzi,

Thanks for reaching out. The lab is designed to facilitate a MITM Attack using BGP Prefix Hijacking. 

![Final Network Topology Design](https://user-images.githubusercontent.com/37820793/189964657-a9f3cbf9-1d09-4f4f-954a-7812abfb760e.png)

The network topology consists of nine autonomous systems ranging from ASN-1 to ASN-9 including the ATTACKER and VICTIM ASes. The VICTIM AS is ASN-2 and the ATTACKER AS is ASN-8. Each autonomous system consists of one router and one server and all the routers are configured to be bgp speakers. Scripts are launched on the servers to execute commands via SSH on the routers to automate the MITM attack or apply prefix filters to prevent the attack. TCP dump is also set up on the DUMP-SERVER of ASN-8 to analyse hijacked traffic intended for ASN-2 once the attack is launched.

Since commands will be executed on the routers via the servers, the device.startup files of each server are used to set up SSH connections between the servers and routers and also write the python programs required to launch the attack and set up the prefix filters on the servers.

The attacker AS (ASN-8) announces 200.7.0.0/24 which is a subnet of the prefix assigned to ASN-2. This announcement will cause the prefix 200.7.0.0/16 and 200.7.0.0/24 to overlap. When prefixes overlap, BGP uses the longest prefix match rule. Due to this rule, announcing 200.7.0.0/24 will cause all the ASes to learn this route thus discarding the route to 200.7.0.0/16 previously learnt from ASN- 2’s announcement. All the traffic intended for ASN-2 will be forwarded to ASN-8. 

A reply path is constructed by declaring a route path to forward the traffic to the VICTIM AS. This ensures that the attack goes unnoticed and prevents the MOAS conflict problem that may cause loops leading network downtime. ASN-8 blinds part of the network to the attack, with the aim of establishing a viable path to the victim. This is achieved by manipulating the AS Path attribute using AS Path Prepending. ASN-8 does this by announcing 200.7.0.0/24 and prepending 5, 1 and 2 to the AS path. AS 5 will not accept a route announcement that has its own AS number 5 hence it will not learn the bogus route announced by ASN-8. All traffic intended for ASN-2 will be intercepted by ASN-8 and forwarded to ASN-2 via the viable path. The dumpserver.startup file creates a python script to launch the attack and construct the the reply path.

The attack can be launched manually by running the following for the bogus announcement:

![Screenshot 2022-09-14 at 10 31 46 AM](https://user-images.githubusercontent.com/37820793/190117912-432ba473-b103-4a0f-8134-e126b25071c8.png)

The following for the as path prepend and route map:
![Screenshot 2022-09-14 at 10 33 27 AM](https://user-images.githubusercontent.com/37820793/190118282-1fe7ea36-3c53-42f3-9407-58a5b2199767.png)

Or with the python script on the dumpserver:
![Screenshot 2022-09-14 at 10 35 51 AM](https://user-images.githubusercontent.com/37820793/190118819-bd658424-0575-4563-a2f2-3e90dd577e6a.png)

NB paramiko is needed to establish the SSH connection and must be installed by creating a custom docker image and running the kathara lab with this image.

For this project prefix lists will be used to prevent and recover from the MITM attack and the type of prefix list to be used is ingress filters. The assumption made here is that ASN-2 has registered 200.7.0.0/16 with the Internet Routing Registry body. This means that other ASes are aware of the legitimate prefix of ASN-2 and so they use this information to create prefix-lists to filter out bogus announcements. Prefix lists are created for each neighbour of the routers and are set to reject prefixes that are greater than or equal to /17.

This can be done manually with the following:
In this example an ingress filter called partialInRouter8 is created for 202.43.176.1 which is a neighbour of router 9. Prefix lists are created for every router in the network except for the attacker AS. This will cause them to discard the bogus announcement from router 8 and fall back to the legitimate route to ASN-2.
![Screenshot 2022-09-14 at 10 45 29 AM](https://user-images.githubusercontent.com/37820793/190121012-d4836561-0178-43d4-a75b-85e1928af5b5.png)

Python scripts to apply prefix lists are created on each of the dumpservers of the routers except the the attacker AS (AS-8).

Please do not hesitate to reach out if you need more information.

**Comment by tcaiazzi** [comment]
Hi @kwaku104,

First of all thanks for your detailed explanation! I really appreciate it! :rocket:

About the custom image, can you please share the Dockerfile? Maybe you can add it to the repository. 

Also, I suggest you to put the explanation in the README, so that people can easily understand the lab. 

Can I add your lab to the community labs list? 
We really love it and we want to enlarge our community! :heart:

**Comment by kwaku104** [comment]
Hi @tcaiazzi 

Yes you can add this lab to the community labs list!

And yes no worries, I will add the Dockerfile for the custom image to the repository and update the README with this detailed explanation.

**Comment by tcaiazzi** [comment]
Hi @kwaku104, 

Many thanks! As you update the lab I will add it to the community labs list :rocket:

**Comment by kwaku104** [comment]
Hi @tcaiazzi,

The lab has been updated now! Thanks.
